# Generated by Django 5.2.17 on 2026-09-12 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("strength", "Strength"),
                            ("cardio", "Cardio"),
                            ("flexibility", "Flexibility"),
                            ("balance", "Balance"),
                        ],
                        default="strength",
                        max_length=20,
                    ),
                ),
                (
                    "muscle_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("chest", "Chest"),
                            ("back", "Back"),
                            ("legs", "Legs"),
                            ("arms", "Arms"),
                            ("shoulders", "Shoulders"),
                            ("core", "Core"),
                            ("full_body", "Full Body"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
